### ISSUE TITLE
creash

### ISSUE THREAD

**Issue by luoxiao** [kishikawakatsumi/KeychainAccess#425] opened 2019-06-05 14:20 UTC
Occasionally, how can I solve it?

![](https://gitbook-1251837863.cos.ap-beijing.myqcloud.com/2019-06-05-142030.png)

**Comment by kishikawakatsumi** [comment] 2019-06-05 14:30
I need more info. Can you share your code that reproduces the crash? @luoxiao

**Comment by luoxiao** [comment] 2019-06-05 14:34
> I need more info. Can you share your code that reproduces the crash? @luoxiao

Hey, this is my screenshot.

https://gitbook-1251837863.cos.ap-beijing.myqcloud.com/2019-06-05-142030.png

**Comment by kishikawakatsumi** [comment] 2019-06-05 14:36
@luoxiao No please share the code that you wrote.

> Maybe caused by multithreading

Probably true

**Comment by luoxiao** [comment] 2019-06-05 14:40
> Probably true

class CrypKeychainCenter: NSObject {

    static var share = CrypKeychainCenter()
    
    func read(_ key:String) -> String? {
        if let str = keyChain[key], str.count > 0,let value = Decode_AES_ECB(str), value.count > 0
        {
            return value
        }
        return nil
    }
    
    func save(_ value:String, key:String) {
        if let result = Endcode_AES_ECB(value), result.count > 0
        {
            try? keyChain.set(result, key: key)
        }
    }
    
    func remove(_ key:String) {
        if let contain = try? keyChain.contains(key), contain {
            try? keyChain.remove(key)
        }
    }
    
}

**Comment by luoxiao** [comment] 2019-06-05 14:45
How should I solve it? Do you have any suggestions?

**Comment by kishikawakatsumi** [comment] 2019-06-06 06:15
You may use it in the wrong way. Can you show the reproducible sample project?

**Comment by gohan4rice** [comment] 2019-06-10 17:02
Any news on this issue? Were there any significant changes in the latest version that could cause this? Apparently I have the same issue. Never managed to reproduce it my self or any of the users but it was caught by an apple employee on the appstore review.

**Comment by kishikawakatsumi** [comment] 2019-06-10 19:11
Please share a reproducible example

**Comment by GG526** [comment] 2019-06-21 03:22
Me too.
![image](https://user-images.githubusercontent.com/11623029/59895333-c8c42580-9416-11e9-9a41-c407f83e1444.png)

**Comment by alexs555** [comment] 2019-07-05 08:50
> Hi. Any news on this issue? Were there any significant changes in the latest version that could cause this? Apparently I have the same issue. Never managed to reproduce it my self or any of the users but it was caught by an apple employee on the appstore review.
> 
> I found another issue on the firebase github repo that looks very similar to this. In my case though, firebase is not mentioned in the symbolicated crash log - [firebase/firebase-ios-sdk#1399](https://github.com/firebase/firebase-ios-sdk/issues/1399)
> 
> The symbolicated crash report: Thread 0 name: Dispatch queue: com.apple.main-thread
> Thread 0 Crashed:
> 0 libsystem_kernel.dylib 0x00000001a76920f4 mach_msg_trap + 8
> 1 libsystem_kernel.dylib 0x00000001a76915a0 mach_msg + 72
> 2 libdispatch.dylib 0x00000001a74f7880 _dispatch_mach_send_and_wait_for_reply + 500 3 libdispatch.dylib 0x00000001a74f7d10 dispatch_mach_send_with_result_and_wait_for_reply$VARIANT$mp + 52 4 libxpc.dylib 0x00000001a7756a04 xpc_connection_send_message_with_reply_sync + 204 5 Security 0x00000001a8767edc securityd_message_with_reply_sync + 96 6 Security 0x00000001a876845c securityd_send_sync_and_do + 80 7 Security 0x00000001a87bdb90 __SecItemDelete_block_invoke_2 + 248 8 Security 0x00000001a87bd2f4 __SecItemAuthDoQuery_block_invoke + 312 9 Security 0x00000001a87bbc60 SecItemAuthDo + 124 10 Security 0x00000001a87bc5f4 SecItemAuthDoQuery + 504 11 Security 0x00000001a87ba284 SecOSStatusWith + 48 12 Security 0x00000001a87bcbe0 SecItemDelete + 448 13 KeychainAccess 0x0000000101b97e0c Keychain.remove(_:) + 48652 (Keychain.swift:724)
> 14 Ronin One 0x000000010102808c RoninConfig.saveToKeyChain(_:toIdentifier:) + 852108 (RoninConfig.swift:121) 15 Ronin One 0x0000000100f8288c specialized static UserController.deleteUserData() + 174220 (UserController.swift:0) 16 Ronin One 0x0000000101082f30 specialized Application.setUserDataFirstTimeAppOpen() + 1224496 (UserController.swift:72) 17 Ronin One 0x0000000100ff723c specialized AppDelegate.application(_:didFinishLaunchingWithOptions:) + 651836 (Application.swift:41)
> 18 Ronin One 0x0000000100ff5fac @objc AppDelegate.application(_:didFinishLaunchingWithOptions:) + 647084 (:41)
> 19 UIKitCore 0x00000001d3c44020 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 412
> 20 UIKitCore 0x00000001d3c45784 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3352

 HI!
Our app also was rejected with the same stacktrace and reason. We were unable to reproduce, but reviewers succeded.

Did you manage the situation? Were you able to pass review?

**Comment by rex3du** [comment] 2019-07-19 01:36
@alexs55 Is there any updates about your submissions or solutions?

**Comment by alexs555** [comment] 2019-07-19 09:42
We just resubmitted binary for review and it passed. weird case.

**Comment by rex3du** [comment] 2019-07-19 23:52
@alexs555 We're not that lukey. We got rejected again when we resubmitted. @kishikawakatsumi Is there any update regarding this crash issue?

**Comment by rex3du** [comment] 2019-07-22 05:24
We ends up with updating this library to v3.2.0 and resubmit it again and it passed the review. I will do update if we still have this crash with later submissions.

**Comment by advaita13** [comment] 2019-09-21 02:21
@kishikawakatsumi 

App got rejected due to similar issue. Cannot reproduce though.
Using v3.1.2 of KeychainAccess.

![Screen Shot 2019-09-21 at 11 10 54](https://user-images.githubusercontent.com/11889814/65366649-d7161d80-dc61-11e9-93c0-590bce952dc9.png)

**Comment by RSickenberg** [comment] 2019-10-08 12:54
Same issue with 3.2.0

**Comment by kishikawakatsumi** [comment] 2019-10-28 05:06
Closing due to no additional info.

**Closed by kishikawakatsumi** 2019-10-28 05:06 UTC
