### ISSUE TITLE
getting error .set throws

### ISSUE THREAD

**Issue by madsonic** [kishikawakatsumi/KeychainAccess#216] opened 2016-06-07 07:07 UTC
`.set` throws an `NSError` instead of `OSStatus` that `SecItemCopyMatching` throws. In this case how do I check for the error that `.set` throws? e.g. errSecSuccess, errSecUserCanceled?

**Comment by kishikawakatsumi** [comment] 2016-07-06 08:28
@madsonic 

`OSStatus` was set to `NSError.code`. You can check it for what kind of error occurred.

To check `errSecUserCanceled`, for example:

```swift
do {
    try keychain.set("01234567-89ab-cdef-0123-456789abcdef", key: "kishikawakatsumi")
} catch let error as NSError {
    switch Status(status: OSStatus(error.code)) {
    case .UserCanceled:
        ...
    default:
        ...
    }
}
```

`errSecSuccess` isn't an error in the library. So `set` doesn't throw any errors, it means `errSecSuccess`. `errSecItemNotFound` is also ignored for simplicity. It's by design.

Is this answer your question?

**Comment by kishikawakatsumi** [comment] 2016-09-14 13:34
@madsonic It was fixed by https://github.com/kishikawakatsumi/KeychainAccess/pull/221/commits/e54025ef360f6c11a5650dd48ce97bbc582b9895

You can catch specific errors as follows:

```
do {
    let string = try keychain.getString("RandomData")
    ...
} catch Status.conversionError {
    ...
} catch {
    ...
}
```

**Closed by kishikawakatsumi** 2016-09-14 13:34 UTC
Labels: help wanted
