### ISSUE TITLE
Error -34018 required entitlement

### ISSUE THREAD

**Issue by arnaudmeunier** [kishikawakatsumi/KeychainAccess#52] opened 2015-02-19 17:11 UTC
Hello,

I'm frequently getting this error:

Error Domain=com.kishikawakatsumi.KeychainAccess.error Code=-34018 "Internal error when a required entitlement isn't present, client has neither application-identifier nor keychain-access-groups entitlements."

I noticed it tends to happen when the application comes back from Background. Any idea where this could come from?

**Comment by kishikawakatsumi** [comment] 2015-02-22 06:11
Could you please show me your code that to get/set keychain items? I think some factors about the error, but I need more details to identify the cause.

**Comment by peacemoon** [comment] 2015-03-20 12:08
I have the same issue with a mac app (running in agent mode). Here are my codes

        let bundleIdentifier = NSBundle.mainBundle().bundleIdentifier
        self.keychain = Keychain(service: bundleIdentifier!)
        if let password = self.keychain!.getString("password") {
            println("Found password = \(password)")
        }
        else {
            println("No password found in keychain")
        }

**Comment by bgreenlee** [comment] 2015-03-30 04:48
I'm seeing this as well. It seems to happen only when updating the keychain item, not when initially creating it. The update succeeds, however.

Here is the relevant code:

```swift
import Cocoa
import KeychainAccess

class PreferencesWindowController: NSWindowController, NSWindowDelegate {

    @IBOutlet weak var usernameTextField: NSTextField!
    @IBOutlet weak var passwordTextField: NSSecureTextField!

    override func windowDidLoad() {
        super.windowDidLoad()

        let defaults = NSUserDefaults.standardUserDefaults()
        let username = defaults.stringForKey("username")
        if username != nil {
            let keychain = Keychain(service: NSBundle.mainBundle().bundleIdentifier!)
            if let password = keychain.get("password") {
                passwordTextField.stringValue = password
            }
        }
        usernameTextField.stringValue = username ?? ""

        //...
    }

    func windowWillClose(notification: NSNotification) {
        let keychain = Keychain(service: NSBundle.mainBundle().bundleIdentifier!)
        let defaults = NSUserDefaults.standardUserDefaults()
        defaults.setValue(usernameTextField.stringValue, forKey: "username")
        keychain.set(passwordTextField.stringValue, key: "password")
        delegate?.preferencesDidUpdate()
    }
}
```

**Comment by arnaudmeunier** [comment] 2015-04-09 00:04
Interesting. I noticed I never had the issue on a production (archived) build. Did you? Might try turning on KeyChain sharing, just to be sure.

**Comment by uchuugaka** [comment] 2015-06-27 05:29
For security, and contrary to Apple's docs, don't update a keychain item, instead, remove it and create a replacement.

**Comment by wangshengjia** [comment] 2015-07-25 14:21
I never had this issue until I update to Swift 2 and test on iOS 9 today, is there something changed in new version?

**Comment by orschaef** [comment] 2015-08-19 14:11
@wangshengjia I experienced the same...after the Swift 2 update.

**Comment by pvegh** [comment] 2015-08-20 08:46
Swift 2 or Xcode 7, not sure which causes the issue, but they both go together.

**Comment by jpaas** [comment] 2015-08-23 17:06
Same here. Swift2 + iOS9.

**Comment by kylejm** [comment] 2015-08-24 16:35
I'm getting this issue with Swift 1.2 and iOS 8. Adding Keychain Sharing worked for fixed me too.

Is enabling Keychain Sharing the correct fix or a bit of a hack around the problem?

**Comment by kylejm** [comment] 2015-08-26 10:57
I've just had this problem re-occue *with* Keychain Sharing enabled. @kishikawakatsumi any ideas of a Fix?

**Comment by kylejm** [comment] 2015-08-27 22:32
This is becoming a *really* frustrating issue for us. I'm able to replicate quite consistently. When running our application after deleting it from the device, we run in to this issue when trying to access the keychain shortly after creating it. During the gap between creating the keychain and receiving this error on next access, the app is exited and re-entered.

@kishikawakatsumi I'm hoping you could advise me on a possible cause and/or fix shortly. I may have to consider finding another keychain wrapper/framework.

**Comment by kylejm** [comment] 2015-08-27 22:45
...now able to replication without exiting the app.

**Comment by kylejm** [comment] 2015-08-28 00:27
Done a fair bit of digging tonight. Looks like this is actually a bug in Security.framework:

https://forums.developer.apple.com/thread/4743

Last response from Apple was on Jul 27, 2015 1:22 AM. They still haven't confirmed a thread for the confirmed bug on this thread.

**Comment by paulbruneau** [comment] 2015-08-28 04:26
This makes sense (that it's an apple bug). Keychain is a mess.

**Comment by lfaoro** [comment] 2015-09-11 23:43
This happens on Mac apps as well, Keychain Sharing fixes it but then you can't distribute the app outside the App Store if you use any of the features under Capabilities

**Comment by fabdarice** [comment] 2015-09-23 02:14
I keep experiencing this as well.
You guys are mentioning that turning on Sharing Capability fixes it.
To turn it on, are you just adding ".synchronizable(true)" to keychain?

**Comment by nickvelloff** [comment] 2015-09-23 04:46
Same issue here as well. "Keychain Sharing" is enabled.

**Comment by lfaoro** [comment] 2015-09-23 07:16
@fabdarice - select your project > Capabilities tab > set Keychain sharing  to On

**Comment by andrew-knott** [comment] 2015-10-03 23:54
Can anyone else confirm that turning on Keychain sharing works? It's still failing for me.

**Comment by nickvelloff** [comment] 2015-10-04 03:15
What is the value for `Keychain` in your `Info.plist`? 
My previous value of `{AppID}.*` did not work any longer after updating to SDK 9 Swift 2. I needed a fully qualified name like `{AppID}.com.domain.app`

**Comment by tomoyuki28jp** [comment] 2015-11-06 02:06
Same issue here :(
Swift2 + iOS9

**Comment by tomoyuki28jp** [comment] 2015-11-07 01:50
It seems like enabling keychain sharing solves this issue for me.

**Comment by lannik** [comment] 2015-11-19 02:46
It seems that the keychain's service identifier should begin with the bundle identifier. Otherwise the system will treat the access from other application, and that's why turning on the keychain sharing can solve this.

**Comment by AlexCatch** [comment] 2015-11-22 17:34
Error is still occurring occasionally.
Swift 2.0 + iOS9

**Comment by kishikawakatsumi** [comment] 2015-11-22 21:56
I cannot reproduce such a problem. Can anyone share a reproducible project? Or could you please report this issue with your code snippets. "Same issue here" is nothing to help for me :bow:

**Comment by kishikawakatsumi** [comment] 2015-11-22 21:58
And @kylejm's mentioned it https://forums.developer.apple.com/thread/4743 . Is it help for this problem?

**Comment by kylejm** [comment] 2015-11-22 22:05
It still happens for me. It happens intermittently when the keychain is accessed after some time has passed since hitting a breakpoint.

In that thread an Apple employee has recently commented saying that we should all file a radar each so that not only can we see the status of the bug being fixed, but it will also go up on Apple's priority. I'm going to do so tomorrow morning when I'm at my desk.

**Comment by paulbruneau** [comment] 2015-11-22 23:17
You can't see the status of other bugs, even ones that you are a dupe of. That is one of the reasons why bugreporter is garbage.

**Comment by madnik** [comment] 2015-12-10 09:50
When a app is installed via testflight and use it for a while (App adding some items to keychain), then I run the app directly to device via Xcode. When the second installation happen on top of the test flight build, I could recreate. May be OS treating a another app in same keychain sharing group. Which make it require key chain sharing on. Thats my guess. Anyone could recreate through this steps?

**Comment by czechboy0** [comment] 2016-01-22 21:22
Just my 2c, I was having this issue in a Mac app and it went away when I ensured I never overwrite an existing value by using this little method:

```swift
extension Keychain {    
    func updateIfNeeded(key: String, value: String?) {
        if self[key] != value {
            self[key] = value
        }
    }
}
```

**Comment by yahmad** [comment] 2016-02-25 18:38
Also seeing this issue in our iOS app. Adding Keychain Sharing didn't fix the issue and clearing storage using .removeAll() before updating also didn't work. Doing individual deleting then re-adding seems to be working, will update if I find out more information.

**Comment by jpaas** [comment] 2016-03-03 14:14
I'm also still having this issue. For me it works fine in the simulator but as soon as I run on a real device it begins failing. I have a super simple singleton class that manages an oauth token for me.

```swift
import KeychainAccess

class Settings {
  
  struct Key {
    static let webServiceAuthToken = "webServiceAuthToken"
  }
  
  class var shared : Settings {
    
    struct Static {
      static let instance = Settings()
    }
    
    return Static.instance
  }
  
  var webServiceBaseUrl: String {
    return NSBundle.mainBundle().infoDictionary!["webServiceBaseUrl"] as! String
  }
  
  var webServiceAuthToken: String? {
    get {
      let keychain = Keychain(service: webServiceBaseUrl)
      do {
        return try keychain.getString(Key.webServiceAuthToken)
      } catch let error {
        log.error("Error getting webServiceAuthToken from keychain: \(error)")
      }
      return nil
    }
    set(value) {
      let keychain = Keychain(service: webServiceBaseUrl)
      if value != nil {
        do {
          try keychain.remove(Key.webServiceAuthToken) // NB: This does seem to help
          try keychain.set(value!, key: Key.webServiceAuthToken)
        } catch let error {
          log.error("Error saving webServiceAuthToken to keychain: \(error)")
        }
      } else {
        do {
          try keychain.remove(Key.webServiceAuthToken)
        } catch let error {
          log.error("Error removing webServiceAuthToken from keychain: \(error)")
        }
      }
    }
  }

```

**Comment by valeIT** [comment] 2016-03-18 10:18
Same here v2.3.3, iOS 9.0.2

**Comment by younanjo** [comment] 2016-03-21 11:39
same error here! It doesn't happen on simulator but on device i can consistently reproduce it.  has anyone been able to find a solution? 

Swift2, ios 9.1

**Comment by mitchellporter** [comment] 2016-03-21 18:12
Where are you guys placing your keychain code? This error started happening to me when I was querying keychain in `applicationDidFinishLaunchingWithOptions`. There has been speculation that this is too early. I moved it to the `viewDidLoad` of my initial view controller and have not experienced the issue since then.

**Comment by amarcadet** [comment] 2016-03-22 10:48
As reported by @hborders https://github.com/matthewpalmer/Locksmith/issues/31 it seems like an Apple bug.

In my case, I got the issue when running from Xcode on the device, but after killing the app and relaunching from the device the error had disappeared.

**Comment by daande** [comment] 2016-03-28 14:44
I was receiving this error I did as @lfaoro suggested and I am no longer seeing it.

**Comment by skreutzberger** [comment] 2016-04-06 18:40
I am suffering under the same issue. I have an app which stores to Keychain but is not distributed to the Mac App Store which means that Keychain Sharing can not be activated.

Does anyone have a fix for that?

**Comment by jpaas** [comment] 2016-04-06 18:44
@skreutzberger From my experience, this problem made keychain unusable for me on real (non-simulator) devices until iOS 9.3 came out.

**Comment by skreutzberger** [comment] 2016-04-06 18:47
@jpaas so it is fixed in 9.3? I am developing for OS X and require 10.11. Seems it is not fixed there, yet?!

**Comment by jpaas** [comment] 2016-04-06 18:48
@skreutzberger yes fixed in iOS 9.3. Sorry I can't speak to OS X. In fact I didn't even know it was problem on OS X too.

**Comment by skreutzberger** [comment] 2016-04-06 18:56
I asked them at [https://forums.developer.apple.com/thread/4743](https://forums.developer.apple.com/thread/4743)

**Comment by skreutzberger** [comment] 2016-04-06 19:02
@jpaas I normally added Keychain support via Capabilities Tab but then I needed to activate Sharing to make it work -> which lead to issues with Mac App Store.

Do you know how I can manually add the minimum necessary entitlements without cloud sharing to Info.plist?

**Comment by jpaas** [comment] 2016-04-06 19:10
@skreutzberger I had the same problem. I could only get it to work by enabling cloud sharing.

**Comment by h3smith** [comment] 2016-04-06 19:11
I maybe missing something obvious, but do you guys have an *.entitlements file that defines your Keychain Access Group[s]?

**Comment by jpaas** [comment] 2016-04-06 19:16
Sorry I mis-spoke. I just looked back at my entitlements, and it seems I was able to get it to work without keychain sharing. I must have turned it off at some point.

**Comment by skreutzberger** [comment] 2016-04-06 20:17
Can you share the content of your entitlements file (maybe with fake values)? I constantly get signing errors on mine. Are you using it for an App Store app?

**Comment by h3smith** [comment] 2016-04-06 20:30
Here is what I have in my entitlements (This is Enterprise and Dev, not App Store, so YMMV)

The first value we use when we share between apps. The 2nd is for app specific keychain storage.

The first value is the prefix + a random value we use (company name)

<img width="581" alt="entitlements" src="https://cloud.githubusercontent.com/assets/1494397/14331766/b267ee4a-fc14-11e5-816b-c212d53837c3.PNG">

**Comment by skreutzberger** [comment] 2016-04-06 20:40
Hmm, looks like mine. 
<img width="489" alt="screenshot 2016-04-06 at 22 36 24" src="https://cloud.githubusercontent.com/assets/564725/14332136/6ab03646-fc48-11e5-9821-7c02b49023e9.png">
<img width="510" alt="screenshot 2016-04-06 at 22 38 53" src="https://cloud.githubusercontent.com/assets/564725/14332147/74fbf658-fc48-11e5-8874-c0ee3e096980.png">

Are you using "Developer ID *" as signing identity?

**Comment by h3smith** [comment] 2016-04-15 13:38
@skreutzberger - yes but without the *. i've randomly gotten the issue (once in a blue moon)

I've noticed in an SDK I use (for another project) that kicks off some keychain access in an initialize method, that if it is invoked in the didFinishLaunchingWithOptions application delegate it would fail virtually every time.

**Comment by skreutzberger** [comment] 2016-04-15 14:03
I fixed the issue by writing an own library which is no-nonsense just-keychain interaction. I will open-source it next week.

**Comment by valeIT** [comment] 2016-04-16 12:47
Please, post it here when you do =)

**Comment by paulbruneau** [comment] 2016-04-16 12:58
Good luck but isn't this project right here a no-nonsense, just keychain interaction? The problem is in Keychain

**Comment by makoni** [comment] 2016-08-23 13:39
[This comment](https://github.com/kishikawakatsumi/KeychainAccess/issues/52#issuecomment-142517512) helped to solve the problem on macOS

**Comment by tolkiana** [comment] 2016-09-12 19:14
Anyone knows a workaround for Unit Tests? I'm facing this problem in Xcode 8 GM. I have tried to add [this](http://stackoverflow.com/questions/20344255/secitemadd-and-secitemcopymatching-returns-error-code-34018-errsecmissingentit/22305193#22305193) to my test target with no luck:

`
codesign --verify --force --sign "$CODE_SIGN_IDENTITY" "$CODESIGNING_FOLDER_PATH"
`

**Comment by twiedow** [comment] 2016-09-14 13:39
Any news for this?
It seems that with iOS 10 this problems always occurs. I just could reproduce the problem when opening the sample app for this project (using the master) and running it in the simulator (iPhone 7 / iPad with iOS 10).

**Comment by kishikawakatsumi** [comment] 2016-09-14 13:53
@twiedow 

> It seems that with iOS 10 this problems always occurs. I just could reproduce the problem when opening the sample app for this project (using the master) and running it in the simulator (iPhone 7 / iPad with iOS 10).

Please add code signing entitlements to the app. I've just fixed at https://github.com/kishikawakatsumi/KeychainAccess/pull/221/commits/fb4529d77f4377cc24bd62f5baf15d6279f9f05f for the example project. From iOS 10, entitlements file is always needed for writing Keychain even without sharing.

<img width="1156" alt="screen shot 2016-09-14 at 22 48 41" src="https://cloud.githubusercontent.com/assets/40610/18514829/040d7066-7ace-11e6-84e2-4e373f53e60c.png">

<img width="679" alt="screen shot 2016-09-14 at 22 53 24" src="https://cloud.githubusercontent.com/assets/40610/18514845/11e36600-7ace-11e6-8a1a-e511509e43cd.png">

**Comment by kishikawakatsumi** [comment] 2016-09-14 13:54
@twiedow Also the example project has been fixed already in `swift-3.0` branch 😉 Thanks!

**Comment by uchuugaka** [comment] 2016-09-14 14:28
Anything that touches security APIs must be code signed properly or it will cause weird failures by design. 
This includes things that call them indirectly. 
Just code sign everything and use proper entitlements.

**Comment by hons82** [comment] 2016-09-21 14:24
@tolkiana I've the same problem... I'm working on a framework with Keychain support, so there is no capabilities Tab... Did u find a solution already?

**Comment by tolkiana** [comment] 2016-09-21 16:01
@hons82 not exactly, my solution was making my tests with mock objects, similar way you would do it with NSUserDefaults.

**Comment by indrajitsinh** [comment] 2016-09-22 10:58
I was receiving this error in iOS 10  I did as @lfaoro suggested and I am no longer seeing it.

**Comment by haaakon** [comment] 2016-09-22 14:50
I'm struggling to find a sulotion to this when using Keychain in Unit tests. Anyone have any tips?

**Comment by petrdvorak** [comment] 2016-09-26 16:36
Guys, a little tiny note - are you sure you want to have "Keychain Sharing" feature on? For my project (related to security element of mobile banking) this is strongly undesired...

**Comment by tolkiana** [comment] 2016-09-26 19:39
@petrdvorak  that's a good point. I found in this [thread](https://forums.developer.apple.com/thread/51071) that just having the entitlements is good enough (if you have at least one of the other capabilities). I just tested, created the entitlements for the Keychain Sharing, then turn it off and then turn on another capability like iCloud for example and still works! I know this is not ideal but I thought maybe is useful for somebody.

**Comment by tolkiana** [comment] 2016-09-26 20:32
For those having problems with Frameworks, the only way I was able to workaround this was by creating a host App. I added a new target, enabled Keychain Sharing in capabilities and then in the test target I selected the Host Application, no need to add the test files to that target:

![screen shot 2016-09-26 at 4 28 42 pm](https://cloud.githubusercontent.com/assets/5129887/18850669/80051f16-8406-11e6-973c-210b066d79d7.png)

**Comment by 1b0t** [comment] 2016-10-01 08:58
If somebody is getting here desperately trying to get it to work without enabling Keychain Sharing. **Just omit the `accessGroup` parameter when creating the `Keychain` object.**

Explicitly passing my bundle id, then creating the entitlements file and adding the code signing entitlements always turned on Keychain sharing automatically. Turning it off again results in Xcode wiping these settings resulting in a deadlock.

**Comment by ovidiomanteiga** [comment] 2016-10-18 15:36
This error also occurs in a project I am currently working on.

# Error
`OSStatus error:[-34018] Internal error when a required entitlement isn't present, client has neither application-identifier nor keychain-access-groups entitlements.`

*NOTE*: The error appears on Xcode console. The app does not crash.

# Facts
1. Xcode version is 8.0 (8A218a).
3. Our project uses Swift version 2.3.
4. Our project uses the version 2.4.0 of this library (https://github.com/kishikawakatsumi/KeychainAccess)
1. The error occurs while running the app in an iOS 10 simulator instance.
2. The error does not occur while running the app in an iOS 9.3 simulator instance.
4. The error occurs either the Keychain instance is created without any arguments or setting just the "storeService" parameter.
5. The error does not occur if the *keychain-access-group* entitlement is set for the target.
6. The error occurs if the entitlements file is set but empty.
6. **The error DOES NOT OCCUR while running the app on an iPhone with iOS 10!!!**

# Hypothesis
**iOS 10 simulator bug.** 😞 

# Related
*  https://forums.developer.apple.com/thread/62847 points to the bug hypothesis.

**Comment by biku** [comment] 2016-10-21 20:02
**if you use .synchronizable(true) try turning iCloud in Capabilities tab and selecting Services: CloudKit**

For me, everything worked fine on simulator. If keychain-access-group entitlement is configured, everything works, remove it and it fails. That until I put it on a device.
After debugging it for hours, reading Apple's thread on devforums I arrived at a conclusion, that iCloud enabling the keychain with .synchronizable(true) is ignored in simulator, but on device - not too fast.
After turning iCloud in Capabilities tab and selecting Services: CloudKit, it started working.
I'm still to verify it in my real app code, currently it is just a library with a prototype app, but it looks promising.

**Comment by x4080** [comment] 2016-10-23 23:44
Here's my experience with it :
- Background : Xcode 8, iOS 10 simulator, iPhone iOS 9.3.3, iPhone iOS 8, free developer certificate (6days limit)
- keychain sharing : on
- simple code : (on button click)
```
        let keychain = Keychain(service: "somewhere")
        keychain["kishikawakatsumi"] = "works"
        let token = keychain["kishikawakatsumi"]
        print(token)
        label.text=token
```

Result :
- iOS simulator : works
- iPhone iOS 8 : works
- iPhone iOS 9.3.3 : works only when running from xcode, not working if the same app is running from device

Is it because of the free developer certificate in iOS 9 that cannot open key chain ? If so why it can work when running from Xcode

Maybe it can help somehow

**Comment by thebluepotato** [comment] 2016-10-24 21:14
From the [Xcode 8.1 GM release notes](http://adcdownload.apple.com/Developer_Tools/Xcode_8.1_GM_Seed/Release_Notes_for_Xcode_8.1_GM_Seed.pdf) : 
>Keychain APIs may fail to work in the Simulator if your entitlements file doesn’t contain a value for the application-identifier entitlement. (28338972)
**Workaround**: Add a user-defined build setting to your target named `ENTITLEMENTS_REQUIRED` and set the value to `YES`. This will cause Xcode to automatically insert an application-identifier entitlement when building.

**Comment by ovidiomanteiga** [comment] 2016-10-28 12:58
@thebluepotato Although Xcode 8.1 Release Notes say exactly the same, I could not make it work yet using Xcode Version 8.1 (8B62)...

**Comment by thebluepotato** [comment] 2016-11-01 12:22
@kishikawakatsumi From the Xcode 8.2 beta release notes : 
>**Resolved in Xcode 8.2 beta - IDE**
>Keychain APIs work correctly in Simulator. (28338972)

**Comment by etayluz** [comment] 2016-11-18 20:42
@thebluepotato have you tried this yet on Xcode 8.2 beta and confirmed that the issue has been resolved?

**Comment by gothedistance** [comment] 2016-11-29 00:47
I encounter same issue yesterday. Probably, it is a simulator bug on XCode8.1.

On my Xcode, when using iOS 10 Device Simualtors(iPhoneSE / iPhone7), this error always shows on console, but does NOT show any errors on using iOS9.x one. 

Here's my code. this works fine with iOS9.x Simualtors, iPhone6s(iOS9.3), iPad Pro(iOS10.1) 

```swift
    let keychain = Keychain(service: "MY SERVICE ID")
    keychain["auth_token"] = token
```

My Background as below. license type may not affect on this error.

- XCode8.1/ Swift3
- Keychain sharing OFF
- install this library via carthage.
- Deployment target 9.0
- Apple Developer Program / Entity Type:Company / Organization

**Comment by forsan** [comment] 2016-11-29 19:44
Same issue here when I use accessGroup and run in real device.

- Xcode 8.1.
- iPhone 6 plus.
- Swift 2.3


and I solved it by adding "App ID prefix" **AB123CDE45**.myKeychainGroup like this
`let keychain = Keychain(service: "name", accessGroup: "W72114R7ZH.com.example")
`

**Comment by hashemp206** [comment] 2016-12-04 10:18
I have enabled keychain sharing. but problem is some times keychain works. and some times can't fetch from from keychain and throws error: "Internal error when a required entitlement isn't present, client has neither application-identifier nor keychain-access-groups entitlements."

does anyone have any idea?

**Comment by ovidiomanteiga** [comment] 2016-12-16 11:09
I have already tried and it worked on Xcode 8.2 (8C38)❗️

**Comment by hashemp206** [comment] 2016-12-18 09:12
I figured it out. my keychain was corrupted. I think because my device is jailbroken

**Comment by kishikawakatsumi** [comment] 2017-02-18 14:40
I believe it was fixed by Xcode 8.2

**Closed by kishikawakatsumi** 2017-02-18 14:40 UTC
Labels: help wanted

**Comment by yuanjilee** [comment] 2018-02-07 08:52
if anyone only crash with `accessGroup`, @forsan  give the true answer!

or you can see directly:  http://evgenii.com/blog/sharing-keychain-in-ios/

**Comment by 8secz-johndpope** [comment] 2020-07-21 06:12
probably spent 10 more minutes on this than necessary 
http://evgenii.com/blog/sharing-keychain-in-ios/

Keychain(service: "com.8secondz.ios.token", accessGroup: "**48K8QNQU37**.8secondz")
this solved the day.
<img width="719" alt="Screen Shot 2020-07-21 at 4 07 17 pm" src="https://user-images.githubusercontent.com/50567111/88019076-48697a00-cb6c-11ea-9358-1addef16fe51.png">

perhaps it would be clearer with a helper to spoon feed clarity 
Keychain(service: "com.8secondz.ios.token", appIdentifier: "48K8QNQU37", groupIdentifier:"8secondz")

**Comment by 520** [comment] 2020-08-19 08:37
Interface of Xcode is a little bit changed in version 11.6. It looks like this. In my case, I use keychain in my watch. I need to add capability of Keychain sharing to watchkit extension and add a group name and fill it into aceessGroup: "Your-App-ID.Your-Group-Name" 
![D21C385D-EB48-47E1-8DA8-16C92CECF2C9](https://user-images.githubusercontent.com/506415/90611928-f20a5c80-e239-11ea-8659-e45a34a855b0.png)
