### ISSUE TITLE
unable to retrieved shared keychain

### ISSUE THREAD

**Issue by littlewings1234** [kishikawakatsumi/KeychainAccess#368] opened 2018-01-24 11:23 UTC
I need to access data in the shared keychain from a notification service extension of an app. However the keychain object retrieved is empty for me. Could you tell me which part I might have done wrong? Thanks.

This is what I did.
1. Add keychain sharing in the main app's capabilities section. Set a name there.
2. Whenever I want to save something in the main app, I initialise the keychain object as follows
var keychain: Keychain = Keychain(service: "serviceName", accessGroup: "10DIGITAPPREPFIX.sharedKeyChain")
In the entitlements file, I can see that there is an item under keychain access group with value:
$(AppIdentifierPrefix)sharedKeyChain
3. In the extension, this is how I initialise the shared keychain object (same as step 2)
var keychain: Keychain = Keychain(service: "serviceName", accessGroup: "10DIGITAPPREPFIX.sharedKeyChain")

In the main app, I can have access to the data in the keychain almost everywhere in the main app's code base.

However, when I try to retrieve the keychain in the extension like step 3, the keychain object is empty, without any keys. 

In step 2, I also tried to initialise it without the access group like:
var keychain: Keychain = Keychain(service: "serviceName")
But it also doesn't work.

I have already verified that the 10 digit app prefix is correct. And the extension and the main app are using provisioning profiles signed under the same team.

I'm just wondering if I might have missed something here. Would appreciate your help a lot!!! Thanks.

Regards, 
Mike

**Comment by neoighodaro** [comment] 2018-03-21 06:15
This same thing is happening to me

**Comment by kishikawakatsumi** [comment] 2018-03-28 20:36
@littlewings1234 @neoighodaro Can you provide reproducible sample code? I cannot see the issue.

**Comment by kishikawakatsumi** [comment] 2018-04-08 14:29
Closing due to no activities. Feel free to reopen if you have further information.

**Closed by kishikawakatsumi** 2018-04-08 14:29 UTC
Labels: help wanted

**Comment by leonid-s-usov** [comment] 2019-03-05 11:03
Were you guys checking this on Simulator?  There's this nasty code 
``` 
            // Access group is not supported on any simulators.
            #if (!arch(i386) && !arch(x86_64)) || (!os(iOS) && !os(watchOS) && !os(tvOS))
            if let accessGroup = self.accessGroup {
                query[AttributeAccessGroup] = accessGroup
            }
            #endif
```

so access group sharing can't be checked on a simulator.
@kishikawakatsumi I've tried to search official docs where it says that keychaing sharing can't be checked on the simulator and couldn't find any. Can you please clarify?
