### ISSUE TITLE
Xcode 9 deprecation warning

### ISSUE THREAD

**Issue by MKGitHub** [kishikawakatsumi/KeychainAccess#333] opened 2017-07-16 14:22 UTC
<img width="1169" alt="2017-07-16 at 16 19 36" src="https://user-images.githubusercontent.com/535550/28248291-b3ee9fb4-6a42-11e7-988d-6bcb9108969e.png">

**Comment by kishikawakatsumi** [comment] 2017-07-20 04:10
Duplicate of https://github.com/kishikawakatsumi/KeychainAccess/issues/255

I can't fix it until removing iOS 8.x support.

**Closed by kishikawakatsumi** 2017-07-20 04:10 UTC
Labels: wontfix
