### ISSUE TITLE
Swift 3.0.1 build, using Carthage

### ISSUE THREAD

**Issue by txaiwieser** [kishikawakatsumi/KeychainAccess#292] opened 2016-10-28 15:39 UTC
I can help to update if you want, just need some directions.

**Comment by andre991** [comment] 2016-10-28 17:17
+1

**Comment by terut** [comment] 2016-10-29 04:48
@txaiwieser Maybe you can use `--no-use-binaries` option. I solved same problem by building the binary by myself.

**Comment by terut** [comment] 2016-10-29 04:52
Maybe you can use `--no-use-binaries` option if you wanna fix soon. I solved same problem by building the binary by myself.

**Comment by andre991** [comment] 2016-10-29 15:49
Ok terut, thanks it's working!

**Comment by kishikawakatsumi** [comment] 2016-10-31 19:27
Closing duplicate of https://github.com/kishikawakatsumi/KeychainAccess/issues/291

**Closed** 2016-10-31 19:27 UTC
