### ISSUE TITLE
Unable to build with Carthage: Scheme KeychainAccess-tvOS is not currently configured for the build action

### ISSUE THREAD

**Issue by Rupert-RR** [kishikawakatsumi/KeychainAccess#189] opened 2015-12-10 16:51 UTC
I won't pretend to know enough about build schemes etc for this, but on trying to update my builds, I get this error:

    Scheme KeychainAccess-tvOS is not currently configured for the build action

I am guessing that this is to do with taking the schemes out of the project file. I can build with version `== 2.3.1`, but not with `~>2.2.0` (which resolves to `2.3.2`) which I was using previously, and, interestingly enough, not with `== 2.2.0` (which says it resolves to `2.2.0`).

My Carthage build command is `carthage update --no-use-binaries --no-skip-current --platform ios`.

Is this perhaps because of not sharing build schemes or some such thing?

**Comment by kishikawakatsumi** [comment] 2015-12-12 20:48
@Rupert-RR What version of Carthage did you use? I cannot reproduce the issue. The above command is succeeded in my environment.

##### Cartfile
```
github "kishikawakatsumi/KeychainAccess"
```

```shell
$ carthage update --no-use-binaries --no-skip-current --platform ios
*** Fetching KeychainAccess
*** Checking out KeychainAccess at "v2.3.2"
*** xcodebuild output can be found in /var/folders/wr/f0q3fd5976nd8fwpwk717btr0000gn/T/carthage-xcodebuild.bxmvTT.log
*** Building scheme "KeychainAccess" in KeychainAccess.xcworkspace
$
```

**Comment by kishikawakatsumi** [comment] 2015-12-20 23:20
I'm closing this issue now because I think Carthage can build this framework, but if you'd like to continue the conversation, feel free to reopen.

**Closed by kishikawakatsumi** 2015-12-20 23:20 UTC

**Comment by zaubara** [comment] 2016-01-28 16:28
Just as a note, I had the exact same issue as Rupert-RR, but was able to build the latest release in a new environment with only one item in the Cartfile. Adding other items did not change the outcome, so I completely removed the Carthage folder and rebuilt everything from scratch - and finally succeeded.
Looks like there are some artifacts left behind that stopped the framework from compiling.
