### ISSUE TITLE
Memory Leaks on iOS 10.1.1

### ISSUE THREAD

**Issue by giofid** [kishikawakatsumi/KeychainAccess#294] opened 2016-11-10 13:29 UTC
Hello,
I used your excellent library in my project but when I profile my app to check for memory leaks, _Instruments_ indicates that there are two leaks.

I attach the stack trace of leaks.
![schermata 2016-11-10 alle 14 23 40](https://cloud.githubusercontent.com/assets/13570450/20178512/cf9013a6-a751-11e6-9f5e-014f3529f087.png)

**Comment by huangboju** [comment] 2016-11-17 06:38
@giofid 
I have leaks too.
<img width="963" alt="2016-11-17 2 34 17" src="https://cloud.githubusercontent.com/assets/14818224/20378819/6b0bd28a-acd3-11e6-8619-4a154fe598f4.png">

<img width="964" alt="2016-11-17 2 33 25" src="https://cloud.githubusercontent.com/assets/14818224/20378821/70cc693c-acd3-11e6-9df0-fbcb1b5d8c9d.png">

**Comment by ybabenko** [comment] 2017-03-15 08:30
I have the same memory leaks.

**Comment by kishikawakatsumi** [comment] 2017-05-31 14:55
@giofid @huangboju @ybabenko Thank you for reporting. I cannot reproduce the issue. Can anyone provide a reproducible project?

**Comment by reza355** [comment] 2018-01-04 06:33
is this solved?

**Comment by kishikawakatsumi** [comment] 2018-01-04 08:48
Please provide reproduction case.

**Comment by kishikawakatsumi** [comment] 2020-04-28 21:51
Closing due to no additional info.

**Closed by kishikawakatsumi** 2020-04-28 21:51 UTC
