### ISSUE TITLE
"unexpectedly found nil while unwrapping an Optional value"

### ISSUE THREAD

**Issue by pdoggi** [kishikawakatsumi/KeychainAccess#302] opened 2017-01-23 17:44 UTC
Thank you for the awesome library! 

Fairly new to Swift and iOS dev, so please bear with me. I'm having trouble with "unexpectedly found nil while unwrapping an Optional value" at the following location:

https://github.com/kishikawakatsumi/KeychainAccess/blob/master/Lib%2FKeychainAccess%2FKeychain.swift#L762

In my app, I'm calling...

```
let keychain = Keychain(service: Bundle.main.bundleIdentifier!)
if keychain.allKeys().contains("some_key_id") {
    // DO something
} else {
    // DO something else
}
```

The code was working fine for awhile, but after an unexpected crash during development, `.allKeys()` started crashing and giving me the nil error. I've tried cleaning and uninstalling to no avail. 

I can bypass the error using `try keychain.contains("some_key_id")`, so it's not urgent, but I would like to figure out why. I don't understand why my code used to work, and now it suddenly doesn't. 

I'll be grateful for any help. Please let me know if you need more info. Thank you!

Connie

**Comment by CMoebius** [comment] 2017-01-30 02:31
I am having getting the same error with allKeys recently. This was working just fine up until today. I added the Firebase/Auth pod and thats when I started having problems. When I remove Firebase, I don't have an issue.

**Comment by pdoggi** [comment] 2017-02-18 00:29
@CMoebius I am using Firebase, so maybe that's what's causing it, but Firebase is critical and I must use it. I hope there will be a fix for the issue, but it's not urgent for me, especially since I'm porting to React Native.

**Comment by CMoebius** [comment] 2017-02-18 00:41
@pdoggi I made a change to the code suggested in another issue and it works fine for me. I won't be able to update the pod until it's fixed though.

**Comment by pdoggi** [comment] 2017-02-18 01:59
@CMoebius Thanks for pointing out the code change! I appreciate it!

**Comment by kishikawakatsumi** [comment] 2017-02-18 14:41
Duplicate of https://github.com/kishikawakatsumi/KeychainAccess/issues/284

**Closed by kishikawakatsumi** 2017-02-18 14:41 UTC
Labels: bug
