### ISSUE TITLE
AccessGroup getting set regardless of initializer 

### ISSUE THREAD

**Issue by ProjectLane** [kishikawakatsumi/KeychainAccess#298] opened 2016-12-12 19:33 UTC
Hello, 

I'm having an issue inside my application where I both want to have a shared keychain, and keep information local to the keychain.

The AccessGroup will be successfully set when initializing:
` keychain = Keychain(service: "sharedService", accessGroup: "XXXXXXXXXX.sharedAccessGroup").accessibility(.afterFirstUnlock)`

The accessGroup property will be correctly set
`
keychain.accessGroup  => XXXXXXXXXX.sharedAccessGroup
`
The description call will show that it's associated with an Access Group
`
keychain.description:
"[\n  [\"service\": \"sharedService\", \"class\": \"GenericPassword\", \"value\": \"35 860307 017724 0\", \"key\": \"someKey\", \"accessGroup\": \"XXXXXXXXXX.sharedAccessGroup\", \"synchronizable\": \"false\", \"accessibility\": \"AfterFirstUnlock\"]\n]”
`

Now when I attempt to initialized a keychain without an accessGroup:
` keychain = Keychain(service: "localService").accessibility(.afterFirstUnlock)`

The accessGroup property will be nil
`
keychain.accessGroup  => nil
`
However, the description call will show that it's associated with an Access Group
`
keychain.description =>
"[\n  [\"service\": \"localService\", \"class\": \"GenericPassword\", \"value\": 3251 bytes, \"key\": \"someKey", \"accessGroup\": \"XXXXXXXXXX.sharedAccessGroup\", \"synchronizable\": \"false\", \"accessibility\": \"AfterFirstUnlock\"]\n]"`

This is with an iPhone 6s Plus running iOS 10.1.1 (14B100)

Is this working as intended?

**Comment by frederic-adda** [comment] 2017-04-25 07:35
I have the same issue with 2 different accessGroups: no matter what accessGroup I use in the initializer, I get the same value when trying to get a key!

Capabilities:
<img width="933" alt="capture d ecran 2017-04-25 a 09 31 22" src="https://cloud.githubusercontent.com/assets/17590846/25373447/f9a6ce9e-2999-11e7-9da8-73cde0b61fe7.png">

```
// Initialize keychains
let completeKeychain = Keychain(service: "fr.lelivrescolaire", accessGroup:    "fr.lelivrescolaire.complete")
let singleBookKeychain = Keychain(service: "fr.lelivrescolaire", accessGroup: "fr.lelivrescolaire.singlebook")

// Write values
completeKeychain["deviceToken"] = "complete1234567890"
singleBookKeychain["deviceToken"] = "singlebook0987654321"

// Print values
print("Complete KC deviceToken: \(String(describing: completeKeychain["deviceToken"]))")
print("SingleBook KC deviceToken: \(String(describing: singleBookKeychain["deviceToken"]))")
```

Result in the console: 
```
Complete KC deviceToken: Optional("singlebook0987654321")
SingleBook KC deviceToken: Optional("singlebook0987654321")
```

Basically, the output is always the last value set fot this key.

Am I doing something wrong? Because if not, that makes KeychainAccess kinda useless when using accessGroups ...
Thanks for your help!

**Comment by frederic-adda** [comment] 2017-04-25 13:36
Ah in my case, I understood what happens: I tested in the simulator ...
Bad idea, the rule is : "never test keychains in the simulator"

**Comment by kishikawakatsumi** [comment] 2017-05-31 14:17
@ProjectLane It's intended behavior.

> When your app creates a keychain item, if you do not explicitly specify the kSecAttrAccessGroup key in the item’s attributes dictionary, Keychain Services uses the first group of the app’s access groups array (ordered as shown above) as the default access group. If your app has a keychain-access-groups entitlement, Keychain Services uses the first of these. Otherwise, it uses the application identifier, which is always present. Thus, by default, unless you add a keychain-access-groups entitlement, an app creates keychain items to which only it has access. On the other hand, all the named access groups from the collection above are valid values for the kSecAttrAccessGroup key. This allows you to add new items to any one of the app’s groups.

https://developer.apple.com/library/content/documentation/Security/Conceptual/keychainServConcepts/02concepts/concepts.html

I'm going to close this issue, if you have further questions, please feel free to reopen it.

**Closed by kishikawakatsumi** 2017-05-31 14:17 UTC
