### ISSUE TITLE
Please update to Swift 4.2

### ISSUE THREAD

**Issue by lvandal** [kishikawakatsumi/KeychainAccess#391] opened 2018-07-17 19:53 UTC
The Carthage bundle will not compile with the latest Xcode 10 beta 4 (10L213o).

`***  Skipped installing KeychainAccess.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.1 (swiftlang-902.0.48 clang-902.0.37.1) and the local version is 4.2 (swiftlang-1000.0.29.2 clang-1000.10.39)."`

Thank you!

**Comment by amelnychuck** [comment] 2018-07-17 21:18
I'm experiencing this as well.

Thanks!

**Comment by kishikawakatsumi** [comment] 2018-07-18 02:48
@lvandal @amelnychuck Duplicate of https://github.com/kishikawakatsumi/KeychainAccess/issues/389
This is not an error.

**Closed by kishikawakatsumi** 2018-07-18 02:48 UTC

**Comment by lvandal** [comment] 2018-07-18 03:13
You're right. Actually, this is the error I'm seeing since the latest Xcode 10 beta:

`*** Building scheme "KeychainAccess" in KeychainAccess.xcworkspace
Build Failed
	Task failed with exit code 70:
	/usr/bin/xcrun xcodebuild -workspace /[...]/Vendor/Carthage/Checkouts/KeychainAccess/KeychainAccess.xcworkspace -scheme KeychainAccess -configuration Release -derivedDataPath /Users/[...]/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10L213o/KeychainAccess/v3.1.1 -sdk watchsimulator -destination platform=watchOS\ Simulator,id=31C70040-2499-4CD8-802B-1952F7564EF2 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /[...]/Vendor/Carthage/Checkouts/KeychainAccess)`

Is it compiling on your end? Thanks!

**Comment by lvandal** [comment] 2018-07-18 03:20
Here's the log file, which seems to show that Xcode is complaining about a missing simulator.

`xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:watchOS Simulator, id:31C70040-2499-4CD8-802B-1952F7564EF2 }
	The requested device could not be found because no available devices matched the request.`

[carthage-xcodebuild.QCWWsc.txt](https://github.com/kishikawakatsumi/KeychainAccess/files/2204242/carthage-xcodebuild.QCWWsc.txt)
