### ISSUE TITLE
Install via Cocoapods fails

### ISSUE THREAD

**Issue by TeunVR** [kishikawakatsumi/KeychainAccess#91] opened 2015-08-11 13:38 UTC
Should be: 
pod 'KeychainAccess', :git => 'https://github.com/kishikawakatsumi/KeychainAccess.git', :branch => 'swift-2.0'

**Comment by kishikawakatsumi** [comment] 2015-08-11 18:36
I cannot reproduce any failures in my environment. Could you please share the entire output of `pod install --verbose`? Thanks!

**Comment by TeunVR** [comment] 2015-08-12 13:59
The problem is i don't have ssh access to github.com set up. Cloning via https works.

$ pod install --verbose
  Preparing

Updating local specs repositories

Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  Already up-to-date.

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-Test`: (``)

Fetching external sources
-> Pre-downloading: `KeychainAccess` from `git@github.com:kishikawakatsumi/KeychainAccess.git`, branch `swift-2.0`
 > Git download
 > Git download
     $ /usr/bin/git clone git@github.com:kishikawakatsumi/KeychainAccess.git /var/folders/y5/89kw41cn0t57g94p66xtsdz80000gn/T/d20150812-30690-1v9pd99 --single-branch --depth 1 --branch swift-2.0
     Cloning into '/var/folders/y5/89kw41cn0t57g94p66xtsdz80000gn/T/d20150812-30690-1v9pd99'...
     Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
     Permission denied (publickey).
     fatal: Could not read from remote repository.
     
     Please make sure you have the correct access rights
     and the repository exists.

[!] Error installing KeychainAccess
[!] /usr/bin/git clone git@github.com:kishikawakatsumi/KeychainAccess.git /var/folders/y5/89kw41cn0t57g94p66xtsdz80000gn/T/d20150812-30690-1v9pd99 --single-branch --depth 1 --branch swift-2.0

Cloning into '/var/folders/y5/89kw41cn0t57g94p66xtsdz80000gn/T/d20150812-30690-1v9pd99'...
Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:130:in `rescue in execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:128:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.9.1/lib/cocoapods-downloader/base.rb:152:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.9.1/lib/cocoapods-downloader/git.rb:65:in `block in clone'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:161:in `block in ui_sub_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:160:in `ui_sub_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.9.1/lib/cocoapods-downloader/git.rb:63:in `clone'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.9.1/lib/cocoapods-downloader/git.rb:29:in `download!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.9.1/lib/cocoapods-downloader/base.rb:80:in `block in download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:145:in `block in ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:144:in `ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.9.1/lib/cocoapods-downloader/base.rb:78:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:110:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:65:in `download_request'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:170:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:153:in `block in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:180:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:180:in `in_tmpdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:152:in `uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:34:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/external_sources/abstract_external_source.rb:108:in `block in pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/external_sources/abstract_external_source.rb:106:in `pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:453:in `fetch_external_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:430:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:429:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:429:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:428:in `fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:69:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:210:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:133:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:132:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:104:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by kishikawakatsumi** [comment] 2015-08-12 14:33
Is your problem resolved? I'm going to close this issue for now, but feel free to reopen it if you have any more questions!

**Closed by kishikawakatsumi** 2015-08-12 14:33 UTC

**Comment by meilers** [comment] 2015-08-24 15:00
I confirm I had the same problem, and:
pod 'KeychainAccess', :git => 'https://github.com/kishikawakatsumi/KeychainAccess.git', :branch => 'swift-2.0'
worked for me
